services:
  nginx:
    container_name: portfolio-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=0
    command: [nginx-debug, '-g', 'daemon off;']
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app-network

  api:
    container_name: portfolio-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DEBUG=true
      - HOST=0.0.0.0
    command: node server.js
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge