services:
  nginx:
    container_name: portfolio-nginx
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=
    restart: unless-stopped
    depends_on:
      - api

  certbot:
    container_name: portfolio-certbot
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx

  api:
    container_name: portfolio-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3002
    command: node server.js
    restart: unless-stopped