# Portfolio API Docker Compose Configuration
version: '3.8'

services:
  # NGINX reverse proxy
  nginx:
    container_name: portfolio-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=api.synergycodelabs.com
    # Removed volume mount to use copied config
    depends_on:
      - api
    networks:
      - portfolio-network
    restart: unless-stopped

  # API service
  api:
    container_name: portfolio-api
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "3002"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DEBUG=true
      - HOST=0.0.0.0
    networks:
      - portfolio-network
    restart: unless-stopped

# Network definition
networks:
  portfolio-network:
    name: portfolio-network
    driver: bridge